name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.75ec6817-cf05-4557-8f4e-a9304057bd54}}
          heroku_app_name: "bloomsapp" #Must be unique in Heroku
          heroku_email: "christykumar13@gmail.com"
